# Generated by Django 4.0.3 on 2022-03-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('creator_name', models.CharField(max_length=100)),
                ('creator_img', models.ImageField(upload_to='creators/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('second_title', models.CharField(max_length=255)),
                ('second_content', models.TextField()),
                ('creator_bio', models.TextField()),
                ('creator_job', models.CharField(max_length=105)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
            },
        ),
    ]
