# Generated by Django 4.0.3 on 2022-03-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_abc_blog_alter_blog_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postt',
        ),
    ]
