# Generated by Django 4.0.3 on 2022-03-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='main_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
