# Generated by Django 4.0.3 on 2022-03-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Main_Title', models.CharField(max_length=50)),
                ('Main_Content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='posts/')),
                ('Title', models.CharField(max_length=50)),
                ('First_Text', models.TextField(blank=True, null=True)),
                ('Second_Text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Main',
            },
        ),
        migrations.CreateModel(
            name='AboutSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('text1', models.CharField(max_length=100)),
                ('text2', models.CharField(max_length=100)),
                ('text3', models.CharField(max_length=100)),
                ('text4', models.CharField(max_length=100)),
                ('text5', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ('-date',),
            },
        ),
    ]
