# Generated by Django 4.0.3 on 2022-03-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutmain_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsubject',
            name='text1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsubject',
            name='text2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsubject',
            name='text3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsubject',
            name='text4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aboutsubject',
            name='text5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
