# Generated by Django 4.0.3 on 2022-03-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutsubject_text1_alter_aboutsubject_text2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsubject',
            options={'ordering': ('date',), 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
